apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry
spec:
  capacity:
    storage: 20Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /temp/hostpath-provisioner/pvc-test
    type: ""
  persistentVolumeReclaimPolicy: Delete
#  storageClassName: standard
