apiVersion: v1
kind: PersistentVolume
metadata:
  name: enmasse-event
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /temp/.hostpath-provisioner/enmasse-event
    type: ""
  persistentVolumeReclaimPolicy: Delete

