hono:
  app:
    maxInstances: 1
    healthCheckPort: 8088
    healthCheckBindAddress: 0.0.0.0
  coap:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
  messaging:
    name: 'Hono COAP Adapter'
    amqpHostname: hono-internal
    host: hono-dispatch-router.hono-test
    port: 5673
    keyPath: /etc/hono/coap-adapter-key.pem
    certPath: /etc/hono/coap-adapter-cert.pem
    trustStorePath: /etc/hono/trusted-certs.pem
  registration:
    name: 'Hono COAP Adapter'
    host: hono-service-device-registry.hono-test
    port: 5671
    credentialsPath: /etc/hono/coap-adapter.credentials
    trustStorePath: /etc/hono/trusted-certs.pem
  credentials:
    name: 'Hono COAP Adapter'
    host: hono-service-device-registry.hono-test
    port: 5671
    credentialsPath: /etc/hono/coap-adapter.credentials
    trustStorePath: /etc/hono/trusted-certs.pem
  tenant:
    name: 'Hono COAP Adapter'
    host: hono-service-device-registry.hono-test
    port: 5671
    credentialsPath: /etc/hono/coap-adapter.credentials
    trustStorePath: /etc/hono/trusted-certs.pem
  command:
    name: 'Hono COAP Adapter'
    amqpHostname: hono-internal
    host: hono-dispatch-router.hono-test
    port: 5673
    keyPath: /etc/hono/coap-adapter-key.pem
    certPath: /etc/hono/coap-adapter-cert.pem
    trustStorePath: /etc/hono/trusted-certs.pem
