hono:
  app:
    maxInstances: 1
    healthCheckPort: 8088
    healthCheckBindAddress: 0.0.0.0
  mqtt:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: /etc/hono/mqtt-adapter-key.pem
    certPath: /etc/hono/mqtt-adapter-cert.pem
  registration:
    name: 'Hono MQTT Adapter'
    host: hono-service-device-registry.hono-test
    port: 5671
    credentialsPath: /etc/hono/mqtt-adapter.credentials
    trustStorePath: /etc/hono/trusted-certs.pem
  credentials:
    name: 'Hono MQTT Adapter'
    host: hono-service-device-registry.hono-test
    port: 5671
    credentialsPath: /etc/hono/mqtt-adapter.credentials
    trustStorePath: /etc/hono/trusted-certs.pem
  tenant:
    name: 'Hono MQTT Adapter'
    host: hono-service-device-registry.hono-test
    port: 5671
    credentialsPath: /etc/hono/mqtt-adapter.credentials
    trustStorePath: /etc/hono/trusted-certs.pem
  messaging:
    name: 'Hono HTTP Adapter'
    host: messaging-0xi8553fe8.hono-test
    port: 5672 
    username: hono
    password: hono_iot_2019
  command:
    name: 'Hono HTTP Adapter'
    host: messaging-0xi8553fe8.hono-test
    port: 5672
    username: hono
    password: hono_iot_2019


