hono:
  app:
    maxInstances: 1
    healthCheckPort: 8088
    healthCheckBindAddress: 0.0.0.0
  kura:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: /etc/hono/kura-adapter-key.pem
    certPath: /etc/hono/kura-adapter-cert.pem
  registration:
    name: 'Hono Kura Adapter'
    host: hono-service-device-registry.hono-test
    port: 5671
    credentialsPath: /etc/hono/kura-adapter.credentials
    trustStorePath: /etc/hono/trusted-certs.pem
  credentials:
    name: 'Hono Kura Adapter'
    host: hono-service-device-registry.hono-test
    port: 5671
    credentialsPath: /etc/hono/kura-adapter.credentials
    trustStorePath: /etc/hono/trusted-certs.pem
  tenant:
    name: 'Hono Kura Adapter'
    host: hono-service-device-registry.hono-test
    port: 5671
    credentialsPath: /etc/hono/kura-adapter.credentials
    trustStorePath: /etc/hono/trusted-certs.pem
  messaging:
    name: 'Hono HTTP Adapter'
    host: messaging-0xi8553fe8.hono-test
    port: 5672 
    username: hono
    password: hono_iot_2019
  command:
    name: 'Hono HTTP Adapter'
    host: messaging-0xi8553fe8.hono-test
    port: 5672
    username: hono
    password: hono_iot_2019
  metrics:
    legacy: true

# disable spring boot actuator endpoints
endpoints:
  enabled: false

management:
  metrics:
    export:
      graphite:
        host: influxdb.hono-test
        port: 2003
