hono:
  app:
    maxInstances: 1
    healthCheckBindAddress: 0.0.0.0
    healthCheckPort: 8088
  auth:
    amqp:
      bindAddress: 0.0.0.0
      keyPath: /etc/hono/auth-server-key.pem
      certPath: /etc/hono/auth-server-cert.pem
      trustStorePath: /etc/hono/trusted-certs.pem
      insecurePortBindAddress: 0.0.0.0
      insecurePortEnabled: true
    svc:
      permissionsPath: file:///etc/hono/permissions.json
